In [7]:
import tensorflow as tf

tf.__version__

'2.0.0'

## 2.2.1 创建tensor ##

In [8]:
x = tf.constant(range(12))
x.shape
x

2022-04-07 09:08:38.705050: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-07 09:08:38.708050: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.


<tf.Tensor: id=0, shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [9]:
len(x)

12

In [10]:
# 把行向量x的形状改为(3,4) = 3行4列的矩阵
X = tf.reshape(x, (3,4))
X

<tf.Tensor: id=2, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [11]:
tf.zeros((2,3,4))

<tf.Tensor: id=5, shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [12]:
tf.ones((3,4))

<tf.Tensor: id=8, shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [13]:
# 通过python列表创建
Y = tf.constant([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
Y

<tf.Tensor: id=9, shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int32)>

In [14]:
# 随机生成元素：eg.均值为0，标准差为1的正太分布
tf.random.normal(shape=[3,4], mean=0, stddev=1)

<tf.Tensor: id=15, shape=(3, 4), dtype=float32, numpy=
array([[-2.855372  ,  2.2007918 ,  1.4462585 , -0.17729796],
       [-0.65255624, -0.03679224, -0.90521675, -1.3783405 ],
       [-0.07747348, -1.4528563 ,  1.7975562 ,  1.7760754 ]],
      dtype=float32)>

## 2.2.2 运算 ##

In [15]:
X + Y

<tf.Tensor: id=16, shape=(3, 4), dtype=int32, numpy=
array([[ 2,  2,  6,  6],
       [ 5,  7,  9, 11],
       [12, 12, 12, 12]], dtype=int32)>

In [16]:
X * Y

<tf.Tensor: id=17, shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  8,  9],
       [ 4, 10, 18, 28],
       [32, 27, 20, 11]], dtype=int32)>

In [17]:
X / Y

<tf.Tensor: id=20, shape=(3, 4), dtype=float64, numpy=
array([[ 0.  ,  1.  ,  0.5 ,  1.  ],
       [ 4.  ,  2.5 ,  2.  ,  1.75],
       [ 2.  ,  3.  ,  5.  , 11.  ]])>

In [19]:
Y = tf.cast(Y, tf.float32)
Y
tf.exp(Y)

<tf.Tensor: id=22, shape=(3, 4), dtype=float32, numpy=
array([[ 7.389056 ,  2.7182817, 54.598152 , 20.085537 ],
       [ 2.7182817,  7.389056 , 20.085537 , 54.598152 ],
       [54.598152 , 20.085537 ,  7.389056 ,  2.7182817]], dtype=float32)>

In [20]:
# 用matmul 做矩阵乘法
Y = tf.cast(Y, tf.int32)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: id=26, shape=(3, 3), dtype=int32, numpy=
array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]], dtype=int32)>

In [21]:
tf.concat([X, Y], axis=0)

<tf.Tensor: id=28, shape=(6, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 2,  1,  4,  3],
       [ 1,  2,  3,  4],
       [ 4,  3,  2,  1]], dtype=int32)>

In [22]:
tf.concat([X, Y], axis=1)

<tf.Tensor: id=30, shape=(3, 8), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  2,  1,  4,  3],
       [ 4,  5,  6,  7,  1,  2,  3,  4],
       [ 8,  9, 10, 11,  4,  3,  2,  1]], dtype=int32)>

In [23]:
tf.equal(X, Y)

<tf.Tensor: id=31, shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [24]:
tf.reduce_sum(X)

<tf.Tensor: id=33, shape=(), dtype=int32, numpy=66>

In [25]:
X = tf.cast(X, tf.float32)
tf.norm(X)

<tf.Tensor: id=39, shape=(), dtype=float32, numpy=22.494444>

## 2.2.3 广播机制 ##

In [29]:

# 定义两个tensor
A = tf.reshape(tf.constant(range(3)),(3,1))
B = tf.reshape(tf.constant(range(2)),(1,2))
A + B


<tf.Tensor: id=53, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

## 2.2.6 tensor 和 numpy 之间相互转换 ##

In [34]:
# numpy转为tensor
import numpy as np
p = np.ones((2, 3))
D = tf.constant(p)
D

<tf.Tensor: id=55, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [35]:
# tensor/NDarray转为numpy实例
np.array(D)

array([[1., 1., 1.],
       [1., 1., 1.]])