In [3]:
import  tensorflow as tf

## 2.3.1 简单示例 ##

In [6]:

x = tf.reshape(tf.Variable(range(4), dtype=tf.float32), (4,1))
x

<tf.Tensor: id=40, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.]], dtype=float32)>

In [5]:
with tf.GradientTape() as t:
    t.watch(x)
    y = 2 * tf.matmul(tf.transpose(x), x)

dy_dx = t.gradient(y, x)
dy_dx

<tf.Tensor: id=30, shape=(4, 1), dtype=float32, numpy=
array([[ 0.],
       [ 4.],
       [ 8.],
       [12.]], dtype=float32)>

## 2.3.2 训练模式和测试模式 ##

In [7]:
with tf.GradientTape(persistent=True) as g:
    g.watch(x)
    y = x * x
    z = y * y
    dz_dx = g.gradient(z, x)
    dz_dx = g.gradient(y, x)
dz_dx, dy_dx

(<tf.Tensor: id=57, shape=(4, 1), dtype=float32, numpy=
 array([[0.],
        [2.],
        [4.],
        [6.]], dtype=float32)>,
 <tf.Tensor: id=30, shape=(4, 1), dtype=float32, numpy=
 array([[ 0.],
        [ 4.],
        [ 8.],
        [12.]], dtype=float32)>)

## 2.3.3 对Python控制流求梯度 ##

In [10]:
def f(a):
     b = a*2
     while tf.norm(b) < 1000:
         b = b * 2
     if tf.reduce_sum(b) > 0:
         c = b
     else:
         c = 100 * b
     return c

In [11]:
a = tf.random.normal((1,1), dtype=tf.float32)
with tf.GradientTape() as t:
    t.watch(a)
    c = f(a)
t.gradient(c, a) == c/a

<tf.Tensor: id=184, shape=(1, 1), dtype=bool, numpy=array([[ True]])>