In [4]:
import tensorflow as tf
import numpy as np

# 4.5.1 Load and save NDarray #

In [5]:
x = tf.ones(3)
x

<tf.Tensor: id=5, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [6]:
# 用save函数和load函数分别存储和读取
np.save('x.npy', x)
x2 = np.load('x.npy')
x2

array([1., 1., 1.], dtype=float32)

In [7]:
y = tf.zeros(4)
np.save('xy.npy',[x,y])
x2, y2 = np.load('xy.npy', allow_pickle=True)
(x2, y2)

/Users/xiaojun/opt/anaconda3/envs/cs224n/lib/python3.7/site-packages/numpy/lib/npyio.py:528: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)


(<tf.Tensor: id=9, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>,
 <tf.Tensor: id=10, shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>)

In [8]:
mydict = {'x':x, 'y':y}
np.save('mydict.npy', mydict)
mydict2 = np.load('mydict.npy', allow_pickle=True)
mydict2

array({'x': <tf.Tensor: id=11, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>, 'y': <tf.Tensor: id=12, shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>},
      dtype=object)

# 4.5.2 Load and save model params #

In [10]:
X = tf.random.normal((2,20))
X

<tf.Tensor: id=18, shape=(2, 20), dtype=float32, numpy=
array([[-0.7330995 , -0.56291944, -0.12986003, -0.12689024,  0.44113392,
         1.1815944 , -1.3673354 , -0.08683849, -1.0950191 ,  0.9323007 ,
         0.13934942,  1.2536501 ,  0.76669407, -0.02038318,  0.99946463,
         1.1244991 ,  0.22590342,  0.05195363, -0.20577738, -0.46588022],
       [-0.7152103 , -0.3720533 ,  0.4783927 , -0.672196  ,  1.0946252 ,
         0.41737843,  0.44257852, -2.1226485 ,  1.1633978 , -0.19509715,
         0.12431203, -1.3453567 , -0.48607233,  1.2110794 , -0.457814  ,
         0.14652139, -0.3439856 ,  2.2889977 ,  1.8381584 , -3.2557578 ]],
      dtype=float32)>

<tf.Tensor: id=24, shape=(2, 20), dtype=float32, numpy=
array([[ 0.31468707, -0.01868811, -0.33625886, -0.8351267 ,  1.3990133 ,
        -0.48506647, -0.7327958 , -1.0225874 , -1.1517107 , -0.22568548,
        -1.4988446 , -1.1472645 , -0.24808969, -1.1621238 , -0.29170945,
        -0.94827676,  1.6446165 , -0.86166084,  0.90304327,  1.405199  ],
       [ 0.41746575, -1.9466873 , -1.2020857 ,  0.7294977 ,  0.14768293,
         0.6693263 ,  1.0076245 , -1.7718576 , -1.2822614 ,  0.59196514,
         0.14573814, -2.115315  ,  0.8629437 , -0.08186237,  1.7318906 ,
         1.5209866 ,  0.42870387, -1.8893027 , -1.1273302 , -0.40710744]],
      dtype=float32)>

In [11]:
class MLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        # Flatten层将除第一维(batch_size)以外的维度展平
        self.flatten = tf.keras.layers.Flatten()
        self.dense1 = tf.keras.layers.Dense(units=256, activation=tf.nn.relu)
        self.dense2 = tf.keras.layers.Dense(units=10)

    def call(self, inputs):
        x = self.flatten(inputs)
        x = self.dense1(x)
        output = self.dense2(x)
        return output

net = MLP()
Y = net(X)
Y

<tf.Tensor: id=80, shape=(2, 10), dtype=float32, numpy=
array([[-0.25537172, -0.37910956,  0.5942322 ,  0.4787952 , -0.2525174 ,
         0.35218835, -0.10567816, -0.16566163, -0.19861428, -0.29335722],
       [-0.64237857, -0.66712224,  0.5723756 , -0.43678156, -0.17873357,
        -0.23313092, -0.6624631 , -0.30150586,  0.23895317,  0.05852423]],
      dtype=float32)>

In [12]:
net.save_weights("4.5saved_model.h5")

In [15]:
# 验证存储和到处的参数是否一致
net2 = MLP()
net2(X)
net2.load_weights("4.5saved_model.h5")
Y2 = net2(X)
Y2 == Y

AttributeError: 'str' object has no attribute 'decode'